name: COINES Installer - MacOS

on:
  push:
    branches:
      - '*'

jobs:
  MacOS-installer:
    runs-on: macos-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          brew upgrade
          brew install libusb gcc make
  
      - name: Create Installer - MacOS
        run: |
          cd _installer_/Installer_Scripts/MacOS
          sh ./gen_install_script.sh

      - name: List the files
        run: |
          find . -type f -name "*.tar.gz"
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coines_macos_installer
          path: ./_installer_/Installer_Scripts/MacOS/_installer_macos.tar.gz


        
    
