name: COINES Installer - Windows

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Download Inno Setup Installer
      run: |
        # Download Inno Setup executable directly
        Invoke-WebRequest -Uri https://jrsoftware.org/isdl.php?file=innosetup-6.2.0.exe -OutFile InnoSetup.exe
        # Ensure the file is downloaded correctly
        if (!(Test-Path .\InnoSetup.exe)) { exit 1 }
    
    - name: Install Inno Setup
      run: |
        # Install Inno Setup silently
        Start-Process -FilePath .\InnoSetup.exe -ArgumentList "/VERYSILENT" -NoNewWindow -Wait
        # Cleanup
        Remove-Item .\InnoSetup.exe -Force

    - name: Run COINES Installer
      run: |
        cd _installer_/Installer_Scripts/Windows
        # Run ISCC to compile the installer
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "COINES_SDK_PRM.iss"
