name: COINESPY deploy on PYPI

on:
  push:
    branches:
      - '*'

jobs:
  coinespy-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          cd _installer_/Installer_Scripts/Linux_generic
          sudo apt update
          sudo apt install libusb-1.0-0-dev gcc make
          sh ./gen_install_script.sh

      - name: List the files
        run: |
          cd __temp
          ls -LR 
        
    
