name: COINESPY deploy on PYPI

on:
  push:
    branches:
      - '*'

jobs:
  coinespy-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          cd _installer_/Installer_Scripts/Linux_generic
          sh ./gen_install_script.sh
        
    
